name: Terraform Apply Google Artifact Registry
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
    apply-artifact-registry:
      permissions: 
        actions: read
        contents: read
      runs-on: ubuntu-latest
      env: 
        tf_actions_working_dir: ./modules/google-artifact-registry
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.6.0
            
        - name: Auth
          uses: google-github-actions/auth@v2
          with: 
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

        - name: Download plan
          uses: actions/download-artifact@v4
          with:
            name: terraform-plan-${{ github.sha }}
        
        - name: Terraform apply
          working-directory: ${{ env.tf_actions_working_dir }}
          run: terraform apply tfplan
